# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-06-02T21:45:05+00:00

from __future__ import annotations

from datetime import date
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class NoteCreate(BaseModel):
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    remind_at: AwareDatetime = Field(..., title='Remind At')


class NoteModelResponse(BaseModel):
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    remind_at: AwareDatetime = Field(..., title='Remind At')
    id: int = Field(..., title='Id')
    user_id: int = Field(..., title='User Id')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class TaskCreate(BaseModel):
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    start_dt: AwareDatetime = Field(..., title='Start Dt')
    end_dt: AwareDatetime = Field(..., title='End Dt')


class TaskDateTimeFilter(BaseModel):
    by_date: date | None = Field(None, title='By Date')
    start_dt: AwareDatetime | None = Field(None, title='Start Dt')
    end_dt: AwareDatetime | None = Field(None, title='End Dt')


class TaskModelResponse(BaseModel):
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    start_dt: AwareDatetime = Field(..., title='Start Dt')
    end_dt: AwareDatetime = Field(..., title='End Dt')
    id: int = Field(..., title='Id')
    state: str = Field(..., title='State')
    user_id: int = Field(..., title='User Id')
    real_start_dt: AwareDatetime | None = Field(..., title='Real Start Dt')
    real_end_dt: AwareDatetime | None = Field(..., title='Real End Dt')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
