# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-06-07T20:45:45+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, EmailStr, Field


class RefreshTokenRequest(BaseModel):
    refresh_token: str = Field(..., title='Refresh Token')


class TokenType(Enum):
    ACCESS = 'access'
    REFRESH = 'refresh'
    SERVICE = 'service'


class ErrorType(Enum):
    EXPIRED_TOKEN = 'expired token'
    WRONG_TOKEN_TYPE = 'wrong token type'
    INVALID_TOKEN = 'invalid token'


class TokenErrorContent(BaseModel):
    detail: str = Field(..., title='Detail')
    token_type: TokenType = Field(..., title='Token Type')
    error_type: ErrorType = Field(..., title='Error Type')


class TokenModelResponse(BaseModel):
    access_token: str = Field(..., title='Access Token')
    refresh_token: str = Field(..., title='Refresh Token')


class UserCreate(BaseModel):
    username: str = Field(..., title='Username')
    email: EmailStr | None = Field(None, title='Email')
    full_name: str | None = Field(None, title='Full Name')
    password: str = Field(..., title='Password')
    tg_id: int | None = Field(None, title='Tg Id')


class UserFromTg(BaseModel):
    username: str = Field(..., title='Username')
    tg_id: int = Field(..., title='Tg Id')


class UserLogin(BaseModel):
    username: str = Field(..., title='Username')
    password: str = Field(..., title='Password')


class UserModelResponse(BaseModel):
    username: str = Field(..., title='Username')
    email: EmailStr | None = Field(None, title='Email')
    full_name: str | None = Field(None, title='Full Name')
    id: int = Field(..., title='Id')
    is_active: bool = Field(..., title='Is Active')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime = Field(..., title='Updated At')
    tg_id: int | None = Field(None, title='Tg Id')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
