name: Process users service contracts update

on:
  push:
    branches:
      - master
    paths:
      - 'schemas/users_service_openapi.json'

jobs:
  generate-pydantic-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout command bot service
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Create schemas dir
        run: mkdir -p schemas

      - name: Generate pydantic models
        run: |
          uvx datamodel-code-generator \
            --input schemas/users_service_openapi.json \
            --output schemas/users_service_contracts.py \
            --input-file-type OpenAPI \
            --output-model-type pydantic_v2.BaseModel

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          commit-message: "update users service token contracts"
          branch: "automation/update-users-service-contracts"
          title: "Users service contracts update"
          body: |
            the users service has updated its token models
            this PR automatically regenerates `schemas/users_service_contracts.py`
          base: master
